name: pack-and-publish-templates-package
on:
  push:
    tags: [ 'templates-v*.*.*' ]
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer'
        required: false
        type: string

jobs:
  tests:
    uses: axelkjonsberg/Azure-UserFlow-Helpers/.github/workflows/tests.yml@master
    secrets: inherit

  publish:
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ (github.ref_type == 'tag' && startsWith(github.ref_name, 'templates-v')) || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Derive package version
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            ver="${GITHUB_REF_NAME#templates-v}"
          else
            ver="${{ inputs.version }}"
          fi
          [[ "$ver" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]] || { echo "Bad SemVer: '$ver'"; exit 1; }
          echo "PACKAGE_VERSION=$ver" >> "$GITHUB_ENV"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Resolve latest Helpers version
        run: |
          helpers_package_id="AxelKjonsberg.AzureUserFlow.Helpers"
          index_url="https://api.nuget.org/v3-flatcontainer/${helpers_package_id,,}/index.json"
          all_versions=$(curl -sSL "$index_url" | jq -r '.versions')
          stable=$(jq -r 'map(select(contains("-")|not)) | last // empty' <<<"$all_versions")
          helpers_version="${stable:-$(jq -r 'last' <<<"$all_versions")}"
          echo "HELPERS_PACKAGE_ID=$helpers_package_id" >> "$GITHUB_ENV"
          echo "HELPERS_VERSION=$helpers_version" >> "$GITHUB_ENV"

      - name: Inject AzureUserFlow.Helpers package ID/version into template.json
        run: |
          tpl="templates/UserFlow.Templates/content/ApiConnector/.template.config/template.json"
          jq --arg id "$HELPERS_PACKAGE_ID" --arg v "$HELPERS_VERSION" \
             '.symbols.UserFlowHelpersPackageId.defaultValue=$id
              | .symbols.UserFlowHelpersVersion.defaultValue=$v' \
             "$tpl" > "$tpl.tmp" && mv "$tpl.tmp" "$tpl"

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true

      - name: Pack
        run: |
          dotnet pack templates/UserFlow.Templates/UserFlow.Templates.csproj \
            -c Release -o ./artifacts /p:PackageVersion="$PACKAGE_VERSION" /p:ContinuousIntegrationBuild=true

      - name: Smoke test
        run: |
          pkg=$(ls artifacts/*.nupkg | head -n1)
          dotnet new install "$pkg"
          mkdir -p smoke && cd smoke
          dotnet new b2c-apiconnector -n SmokeTest -o .
          proj=$(echo src/*.csproj)
          dotnet restore "$proj"
          dotnet build "$proj" -c Release

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "artifacts/*.nupkg" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
