name: pack-and-publish-templates
on:
  push:
    tags: [ 'templates-v*.*.*' ]

jobs:
  tests:
    uses: axelkjonsberg/Azure-UserFlow-Helpers/.github/workflows/tests.yml@master
    secrets: inherit

  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Resolve latest published UserFlow.Helpers version
        run: |
          helpers_id="AxelKjonsberg.AzureUserFlow.Helpers"
          index_url="https://api.nuget.org/v3-flatcontainer/${helpers_id,,}/index.json"
          all_versions=$(curl -sSL "$index_url" | jq -r '.versions')
          stable_version=$(jq -r 'map(select(contains("-")|not)) | last // empty' <<<"$all_versions")
          helpers_version="${stable_version:-$(jq -r 'last' <<<"$all_versions")}"
          echo "HELPERS_VERSION=$helpers_version" >> "$GITHUB_ENV"

      - name: Use UserFlow.Helpers package version and ID in the template config
        run: |
          tpl="templates/UserFlow.Templates/content/ApiConnector/.template.config/template.json"
          jq --arg id "$helpers_id" --arg v "$helpers_version" \
          '.symbols.UserFlowHelpersPackageId.defaultValue = $id
          | .symbols.UserFlowHelpersVersion.defaultValue = $v' \
          "$tpl" > "$tpl.tmp" && mv "$tpl.tmp" "$tpl"

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true

      - name: Pack template (use tag as version)
        run: |
          VERSION="${GITHUB_REF_NAME#templates-v}"
          dotnet pack templates/UserFlow.Templates/UserFlow.Templates.csproj \
            -c Release -o ./artifacts /p:PackageVersion="$VERSION" /p:ContinuousIntegrationBuild=true

      - name: Smoke test – install template nupkg and build a project
        run: |
          PKG=$(ls artifacts/*.nupkg | head -n1)
          dotnet new install "$PKG"
          mkdir -p smoke && cd smoke
          dotnet new b2c-apiconnector -n SmokeTest
          dotnet restore
          dotnet build -c Release
        # dotnet new install allows path or NUGET_ID::version

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "artifacts/*.nupkg"  --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          dotnet nuget push "artifacts/*.snupkg" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
