name: pack-and-publish-helpers-package
on:
  push:
    tags: [ 'helpers-v*.*.*' ]
  workflow_dispatch:

jobs:
  tests:
    uses: axelkjonsberg/Azure-UserFlow-Helpers/.github/workflows/tests.yml@master
    secrets: inherit

  publish:
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'helpers-v') }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Derive package version from tag
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" != "tag" ]]; then
            echo "This job must run on a tag ref"; exit 1; fi
          case "${GITHUB_REF_NAME}" in
            helpers-v*) PACKAGE_VERSION="${GITHUB_REF_NAME#helpers-v}" ;;
            *) echo "Unexpected tag '${GITHUB_REF_NAME}'"; exit 1 ;;
          esac
          [[ "$PACKAGE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-.+)?$ ]] || { echo "Bad SemVer: $PACKAGE_VERSION"; exit 1; }
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true

      - name: Pack
        run: |
          dotnet pack UserFlow.Helpers/UserFlow.Helpers.csproj -c Release --no-build -o ./artifacts \
            -p:PackageVersion="$PACKAGE_VERSION" -p:Version="$PACKAGE_VERSION" -p:ContinuousIntegrationBuild=true

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "artifacts/*.nupkg"  --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          shopt -s nullglob; for f in artifacts/*.snupkg; do
            dotnet nuget push "$f" --api-key "$NUGET_API_KEY" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          done
