name: tests
on:
  workflow_call:
  pull_request:
  push:
    branches: [ main ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore /p:ContinuousIntegrationBuild=true
      - run: dotnet test -c Release --no-build --logger "trx;LogFileName=test.trx"
